# SPDX-FileCopyrightText: 2021 Aaron Dewes <aaron.dewes@protonmail.com>
#
# SPDX-License-Identifier: AGPL-3.0-only

# yaml-language-server: $schema=../../app-standard-v3.yml

version: 3

metadata:
  category: Wallet Servers
  name: BlueWallet Lightning
  version: 1.4.1
  tagline: Connect BlueWallet to your Lightning node
  description: >-
    Run BlueWallet in the most private and secure way possible by removing
    3rd parties and connecting it directly to your Citadel's Lightning node.
    You can pair multiple BlueWallet accounts, so your friends and family can pair
    their BlueWallet with your Citadel for a trust-minimized setup.
  developers: 
    BlueWallet: https://lndhub.io
  dependencies:
  - lnd
  repo: https://github.com/BlueWallet/LndHub
  support: https://t.me/bluewallet
  gallery:
  - 1.jpg
  - 2.jpg
  - 3.jpg

containers:
- name: main
  image: bluewalletorganization/lndhub:v1.4.1@sha256:db673a8d360982984d05f97303e26dc0e5a3eea36ba54d0abdae5bbbeef31d3a
  depends_on:
  - redis
  port: 3000
  environment:
    PORT: 3000
    TOR_URL: ${APP_HIDDEN_SERVICE}
    LND_CERT_FILE: /lnd/tls.cert
    LND_ADMIN_MACAROON_FILE: /lnd/data/chain/bitcoin/${BITCOIN_NETWORK}/admin.macaroon
    CONFIG: >
      { 
        "rateLimit": 10000,
        "postRateLimit": 10000,
        "redis": {
          "port": 6379,
          "host": "$APP_BLUEWALLET_REDIS_IP",
          "family": 4,
          "password": "moneyprintergobrrr",
          "db": 0
        },
        "lnd": {
          "url": "$LND_IP:$LND_GRPC_PORT",
          "password": ""
        }
      }
  # Some stuff for the container to run securely & stop properly
  user: 1000:1000
  init: true
  restart: "on-failure"

- name: redis
  image: redis:6.2.6-bullseye@sha256:0c0484b1d1ff36faace984fe9d8e0fe58892ecc34a4859b97171045b9cd343e1
  command: redis-server --requirepass moneyprintergobrrr
  data:
  - data/redis:/data
  user: 1000:1000
  init: true