citadel_version: 4
metadata:
  name: Agora
  version: v0.1.2
  category: Files
  tagline: Sell your files for Bitcoin
  developers:
    Casey Rodarmor & Sönke Hahn: https://agora-org.github.io/agora/
  permissions:
  - lnd
  repo:
    Public: https://github.com/agora-org/agora
  support: https://t.me/agoradiscussion
  gallery:
  - 1.jpg
  - 2.jpg
  - 3.jpg
  path: /admin/
  defaultPassword: $APP_SEED
  torOnly: false
  description: Agora is a project that allows anyone to sell files on the web for bitcoin using the Lightning Network.\n\nAgora serves the contents of a local directory, providing file listings and downloads over HTTP. For example, you can point it at a directory full of PDFs, allowing users to browse and view the PDFs in their web browser. If Agora is connected to an LND node, it can be configured to require Lightning Network payments for downloads.
services:
  main:
    image: nginx:1.21.6@sha256:2834dc507516af02784808c5f48b7cbe38b8ed5d0f4837f16e78d00deb7e7767
    depends_on:
    - agora
    - filebrowser
    restart: on-failure
    init: true
    port: 80
    mounts:
      data:
        data/nginx.conf: /etc/nginx/nginx.conf
        data/www: /usr/share/nginx/html
  agora:
    image: ghcr.io/agora-org/agora:sha-bb037f2@sha256:ab5538638fa5c6c709c5dd295df1dd57e419abdbd2328075843ce6fbe0951820
    user: 1000:1000
    stop_grace_period: 1m
    restart: on-failure
    environment:
      LND_RPC_AUTHORITY: $APP_LND_SERVICE_IP:10009
      FILES_DIR: /files
      TLS_CERT_PATH: /lnd/tls.cert
      INVOICES_MACAROON_PATH: /lnd/data/chain/bitcoin/$BITCOIN_NETWORK/invoice.macaroon
      AGORA_PORT: '8080'
    mounts:
      lnd: /lnd
      data:
        data/files: /files
  filebrowser:
    image: filebrowser/filebrowser:v2.21.1@sha256:e1f43b1b8a1acb1d7cd5f934454e7a2ef571ea3bab48b0e1ed0fa97ef9df8d69
    user: 1000:1000
    stop_grace_period: 1m
    restart: on-failure
    entrypoint: sh /citadel-entrypoint.sh
    environment:
      APP_PASSWORD: $APP_SEED
    mounts:
      data:
        data/database/filebrowser.db: /database.db
        data/entrypoint.sh: /citadel-entrypoint.sh
        data/files: /srv
