citadel_version: 4
metadata:
  name: Fulcrum
  version: 1.8.1
  category: Electrum Servers
  tagline: Fast Electrum server
  developers:
    Calin Culianu: https://github.com/cculianu/Fulcrum
  description: Fulcrum is a very fast Electrum server. While it's faster than Electrs, it uses more CPU, RAM and disk space.
  permissions:
  - bitcoind
  repo:
    Public: https://github.com/cculianu/Fulcrum
  support: https://t.me/runcitadel
  gallery:
  - 1.jpg
  - 2.jpg
  - 3.jpg
  defaultPassword: null
  torOnly: false
  implements: electrum
services:
  service:
    image: cculianu/fulcrum:latest@sha256:c0543f8b8a5bf6b0c447d8525d6b4360a6c07532f7741f19cc2c179968e71848
    stop_grace_period: 5m
    restart: on-failure
    command: /usr/bin/Fulcrum /data/fulcrum.conf
    mounts:
      data:
        data: /data
        fulcrum.conf: /data/fulcrum.conf
    environment:
      RPCUSER: $BITCOIN_RPC_USER
      RPCPASSWORD: $BITCOIN_RPC_PASS
    required_ports:
      tcp:
        50001: 50001
        50003: 50003
    hidden_services:
      50001: 50001
      50003: 50003
  main:
    image: ghcr.io/runcitadel/electrum-ui:main@sha256:eea9424e5a987fb2e6a4e6929b3c534ad2943df18c4766a0d71f73073ebff067
    init: true
    port: 8000
    environment:
      BITCOIN_IP: $BITCOIN_IP
      BITCOIN_RPC_PORT: $BITCOIN_RPC_PORT
      BITCOIN_RPC_USER: $BITCOIN_RPC_USER
      BITCOIN_RPC_PASS: $BITCOIN_RPC_PASS
      ELECTRUM_IP: $APP_FULCRUM_SERVICE_IP
      ELECTRUM_PORT: 50001
    restart: on-failure
