citadel_version: 4
metadata:
  name: LNDHub.go
  version: 0.9.0
  category: Wallet Servers
  tagline: Give access to BlueWallet & Alby for friends
  developers:
    Alby: https://getalby.com
  permissions:
  - lnd
  repo:
    Public: https://github.com/getAlby/lndhub.go
  support: https://t.me/getalby
  gallery:
  - 1.jpg
  - 2.jpg
  - 3.jpg
  defaultPassword: null
  torOnly: false
  description: "Run BlueWallet & Alby in the most private and secure way possible by removing 3rd parties and connecting it directly to your Citadel's Lightning node.\n\nThis app automatically manages accounts, so you can easily share your node with friends and family. "
services:
  main:
    image: ghcr.io/runcitadel/lndhub.go:main@sha256:ab0eb387a731d0ff067dc04075aebeeda6b967473499f01adcc26d0942d7c0aa
    user: 1000:1000
    restart: on-failure
    entrypoint: /entry.sh
    environment:
      JWT_SECRET: $APP_SEED
      DATABASE_URI: postgresql://citadel:freedom@$APP_LNDHUB_POSTGRES_IP:5432/lndhub?sslmode=disable
      LND_ADDRESS: $APP_LND_SERVICE_IP:10009
    port: 3000
    mounts:
      lnd: /lnd
      data:
        entry.sh: /entry.sh
  postgres:
    image: postgres:14.4-bullseye
    user: 1000:1000
    environment:
      POSTGRES_DB: lndhub
      POSTGRES_PASSWORD: freedom
      POSTGRES_USER: citadel
    mounts:
      data:
        data/postgres: /var/lib/postgresql/data
