citadel_version: 4
metadata:
  name: code-server
  version: 4.10.1
  category: Development
  tagline: Run VS Code on your Citadel
  developers:
    Coder: https://coder.com
  description: This app doesn't  have a description yet.
  permissions: []
  repo:
    Public: https://github.com/cdr/code-server
  support: https://github.com/cdr/code-server/discussions
  gallery:
  - 1.jpg
  - 2.jpg
  - 3.jpg
  defaultPassword: $APP_SEED
services:
  main:
    image: codercom/code-server:4.10.1@sha256:68b4c30ec27e835391020db0287f071f174ee688376aefe71003d60edc9ff728
    user: 1000:1000
    environment:
      PASSWORD: $APP_SEED
    port: 8080
    mounts:
      data:
        data: /home/coder
