# SPDX-FileCopyrightText: 2021 Oren Zomer
#
# SPDX-License-Identifier: AGPL-3.0-only

# yaml-language-server: $schema=../../app-standard-v3.yml

version: 3

metadata:
  category: Social
  name: Krystal Bull
  version: 1.7.0-212-d9126650
  tagline: Become an oracle and create Bitcoin bets
  description: >-
    Krystal Bull allows you to become a Bitcoin oracle. An oracle allows information from the real world
    (financial markets, sporting events, elections, etc) to be used to create and settle Bitcoin bets.


    The oracle is a crucial component for Discreet Log Contracts (DLC).
    Without a trustworthy oracle, you cannot create a bet on Bitcoin using DLCs.
    Trustworthy oracles are a building block to realizing Bitcoin DeFi.
    
    
    To see some example oracles, please visit oracle.suredbits.com.
    
    
    WARNING: This version of Krystal Bull is an early alpha release for testing.
    It's not secure, please don't use it for anything serious.
  developers: 
    SuredBits: https://suredbits.com/
  dependencies: []
  repo: https://github.com/bitcoin-s/krystal-bull
  support: https://join.slack.com/t/suredbits/shared_invite/zt-eavycu0x-WQL7XOakzQo8tAy7jHHZUw
  gallery: 
      - 1.jpg
      - 2.jpg
      - 3.jpg

containers:
  - name: main
    image: bitcoinscala/oracle-server-ui:0.0.1-864a9f4a-SNAPSHOT
    user: "1000:1000"
    stop_grace_period: 1m
    environment:
      ORACLE_SERVER_API_URL: "http://${APP_KRYSTAL_BULL_ORACLESERVER_IP}:9998/"
      TOR_PROXY: socks5://${TOR_PROXY_IP}:${TOR_PROXY_PORT}
    depends_on: 
      - oracleserver
    port: 3001
  - name: oracleserver
    image: bitcoinscala/bitcoin-s-oracle-server:1.7.0-212-d9126650-SNAPSHOT
    user: "1000:1000"
    data:
      - data/oracleserver:/home/bitcoin-s/.bitcoin-s
    environment:
      BITCOIN_S_KEYMANAGER_ENTROPY: $APP_SEED