citadel_version: 4
metadata:
  name: Oak Node
  version: 0.3.4
  category: Automation
  tagline: Do more with your LND node
  developers:
    Carlos: https://oak-node.net
  permissions:
  - lnd
  repo:
    Public: https://oak-node.net
  support: https://oak-node.net/forum
  gallery:
  - 1.jpg
  - 2.jpg
  - 3.jpg
  defaultPassword: null
  torOnly: false
  description: |-
    Oak Node gives you Scheduled Payments. Now you can send sats to a Lightning Address on a schedule.  Support your favorite content creators every week, every day, or even every block! Up to you.

    Oak Node also includes an optional bot module for more advanced users.
services:
  web:
    image: oak-node.net/oak:v0.3.4@sha256:b4f218a453a10174492a1b03c66329dff89bdece26c0b024e1bffe9340141048
    user: 1000:1000
    stop_grace_period: 1m
    restart: on-failure
    environment:
      OAK_LND_MACAROON_PATH: /lnd-dir/data/chain/bitcoin/$BITCOIN_NETWORK/admin.macaroon
      OAK_DATA_DIR: /data
      OAK_LND_CERT_PATH: /lnd-dir/tls.cert
      OAK_LND_REST_API_URL: https://$APP_LND_SERVICE_IP:8080
      ROCKET_ADDRESS: 0.0.0.0
      ROCKET_PORT: '8100'
    port: 8100
    mounts:
      lnd: /lnd-dir
      data:
        log: /oak/log
        data: /data
