citadel_version: 4
metadata:
  name: LnVisualizer
  version: 0.0.27
  category: Explorers
  tagline: View the Lightning Network from your node's perspective
  developers:
    Max Kotlan: https://lnvisualizer.com
  description: Your Lightning node is continuously receiving, storing, and transmitting graph information. LnVisualizer takes this data and transforms it into an interactive, 3D graph. Search for nodes, filter the graph, and write custom queries to help understand your position in the network.
  permissions:
  - lnd
  repo:
    Public: https://github.com/MaxKotlan/LN-Visualizer
  support: lnvisualizer@gmail.com
  gallery:
  - 1.jpg
  - 2.jpg
  - 3.jpg
  path: ''
  defaultPassword: null
  torOnly: false
services:
  api:
    image: maxkotlan/ln-visualizer-api:v0.0.20@sha256:cfea255f3343dbacf96c5470dcd442f1cc034337dfb46ecfbbc6d5c1978da1a4
    user: 1000:1000
    stop_grace_period: 1m
    restart: on-failure
    environment:
      LND_CERT_FILE: /lnd/tls.cert
      LND_SOCKET: ${APP_LND_SERVICE_IP}:10009
      LND_MACAROON_FILE: /lnd/data/chain/bitcoin/${BITCOIN_NETWORK}/readonly.macaroon
    mounts:
      lnd: /lnd
    direct_tcp: false
  main:
    image: maxkotlan/ln-visualizer-web:v0.0.27@sha256:b9bac717ba4e8f7aa4c4ac3a25fb1d0d261e7db67f46b0b28c8d17e6b44ea079
    stop_grace_period: 1m
    restart: on-failure
    environment:
      LN_VISUALIZER_API_URL: http://${APP_LN_VISUALIZER_API_IP}:5647
    port: 80
    direct_tcp: false
