citadel_version: 4
metadata:
  name: WoofBot
  version: 0.6.0
  category: Explorers
  tagline: A chatbot for your personal node.
  developers:
    WoofBotApp: https://github.com/woofbotapp
  description: 'WoofBot is a chat bot that runs on your personal Bitcoin node and sends telegram notifications based on pre-configured conditions: addresses, transactions, new-blocks and price changes.'
  permissions:
  - bitcoind
  repo:
    Public: https://github.com/woofbotapp/woofbotapp
  support: https://github.com/woofbotapp/woofbotapp/discussions
  gallery:
  - 1.jpg
  - 2.jpg
  - 3.jpg
  path: ''
  defaultPassword: $APP_SEED
  torOnly: false
services:
  mongodb:
    image: mongo:5.0.9@sha256:37e84d3dd30cdfb5472ec42b8a6b4dc6ca7cacd91ebcfa0410a54528bbc5fa6d
    user: 1000:1000
    stop_grace_period: 1m
    restart: on-failure
    mounts:
      data:
        data/db: /data/db
    direct_tcp: false
  main:
    image: woofbot/woofbot:v0.6.0@sha256:9a3b2035613958be9d2ba5f68d2c793fcc47bbd3cfddf4122b39d01d240b3504
    stop_grace_period: 1m
    depends_on:
    - mongodb
    restart: on-failure
    environment:
      APP_BITCOIN_RPC_USER: $BITCOIN_RPC_USER
      APP_PASSWORD: $APP_SEED
      APP_BITCOIN_NODE_IP: $BITCOIN_IP
      APP_BITCOIN_RPC_PASS: $BITCOIN_RPC_PASS
      MONGODB_URI: mongodb://${APP_WOOFBOT_MONGODB_IP}:27017/woofbot
      APP_SEED: $APP_SEED_2
      APP_PORT: '8080'
      APP_BITCOIN_RPC_PORT: $BITCOIN_RPC_PORT
    port: 8080
    direct_tcp: false
